/*
 * Automatically generated by ./lib/build_OID_registry.  Do not edit
 */

static const unsigned short oid_index[OID__NR + 1] = {
	[OID_id_dsa_with_sha1] = 0,
	[OID_id_dsa] = 7,
	[OID_id_ecdsa_with_sha1] = 14,
	[OID_id_ecPublicKey] = 21,
	[OID_rsaEncryption] = 28,
	[OID_md2WithRSAEncryption] = 37,
	[OID_md3WithRSAEncryption] = 46,
	[OID_md4WithRSAEncryption] = 55,
	[OID_sha1WithRSAEncryption] = 64,
	[OID_sha256WithRSAEncryption] = 73,
	[OID_sha384WithRSAEncryption] = 82,
	[OID_sha512WithRSAEncryption] = 91,
	[OID_sha224WithRSAEncryption] = 100,
	[OID_data] = 109,
	[OID_signed_data] = 118,
	[OID_email_address] = 127,
	[OID_contentType] = 136,
	[OID_messageDigest] = 145,
	[OID_signingTime] = 154,
	[OID_smimeCapabilites] = 163,
	[OID_smimeAuthenticatedAttrs] = 172,
	[OID_md2] = 183,
	[OID_md4] = 191,
	[OID_md5] = 199,
	[OID_msIndirectData] = 207,
	[OID_msStatementType] = 217,
	[OID_msSpOpusInfo] = 227,
	[OID_msPeImageDataObjId] = 237,
	[OID_msIndividualSPKeyPurpose] = 247,
	[OID_msOutlookExpress] = 257,
	[OID_certAuthInfoAccess] = 266,
	[OID_sha1] = 274,
	[OID_sha256] = 279,
	[OID_sha384] = 288,
	[OID_sha512] = 297,
	[OID_sha224] = 306,
	[OID_commonName] = 315,
	[OID_surname] = 318,
	[OID_countryName] = 321,
	[OID_locality] = 324,
	[OID_stateOrProvinceName] = 327,
	[OID_organizationName] = 330,
	[OID_organizationUnitName] = 333,
	[OID_title] = 336,
	[OID_description] = 339,
	[OID_name] = 342,
	[OID_givenName] = 345,
	[OID_initials] = 348,
	[OID_generationalQualifier] = 351,
	[OID_subjectKeyIdentifier] = 354,
	[OID_keyUsage] = 357,
	[OID_subjectAltName] = 360,
	[OID_issuerAltName] = 363,
	[OID_basicConstraints] = 366,
	[OID_crlDistributionPoints] = 369,
	[OID_certPolicies] = 372,
	[OID_authorityKeyIdentifier] = 375,
	[OID_extKeyUsage] = 378,
	[OID_gostCPSignA] = 381,
	[OID_gostCPSignB] = 388,
	[OID_gostCPSignC] = 395,
	[OID_gost2012PKey256] = 402,
	[OID_gost2012PKey512] = 410,
	[OID_gost2012Digest256] = 418,
	[OID_gost2012Digest512] = 426,
	[OID_gost2012Signature256] = 434,
	[OID_gost2012Signature512] = 442,
	[OID_gostTC26Sign256A] = 450,
	[OID_gostTC26Sign256B] = 459,
	[OID_gostTC26Sign256C] = 468,
	[OID_gostTC26Sign256D] = 477,
	[OID_gostTC26Sign512A] = 486,
	[OID_gostTC26Sign512B] = 495,
	[OID_gostTC26Sign512C] = 504,
	[OID_sm2] = 513,
	[OID_sm3] = 521,
	[OID_SM2_with_SM3] = 529,
	[OID_sm3WithRSAEncryption] = 537,
	[OID__NR] = 545
};

static const unsigned char oid_data[545] = {
	42, 134, 72, 206, 46, 4, 3, 	// id_dsa_with_sha1
	42, 134, 72, 206, 56, 4, 1, 	// id_dsa
	42, 134, 72, 206, 61, 4, 1, 	// id_ecdsa_with_sha1
	42, 134, 72, 206, 61, 2, 1, 	// id_ecPublicKey
	42, 134, 72, 134, 247, 13, 1, 1, 1, 	// rsaEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 2, 	// md2WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 3, 	// md3WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 4, 	// md4WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 5, 	// sha1WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 11, 	// sha256WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 12, 	// sha384WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 13, 	// sha512WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 1, 14, 	// sha224WithRSAEncryption
	42, 134, 72, 134, 247, 13, 1, 7, 1, 	// data
	42, 134, 72, 134, 247, 13, 1, 7, 2, 	// signed_data
	42, 134, 72, 134, 247, 13, 1, 9, 1, 	// email_address
	42, 134, 72, 134, 247, 13, 1, 9, 3, 	// contentType
	42, 134, 72, 134, 247, 13, 1, 9, 4, 	// messageDigest
	42, 134, 72, 134, 247, 13, 1, 9, 5, 	// signingTime
	42, 134, 72, 134, 247, 13, 1, 9, 15, 	// smimeCapabilites
	42, 134, 72, 134, 247, 13, 1, 9, 16, 2, 11, 	// smimeAuthenticatedAttrs
	42, 134, 72, 134, 247, 13, 2, 2, 	// md2
	42, 134, 72, 134, 247, 13, 2, 4, 	// md4
	42, 134, 72, 134, 247, 13, 2, 5, 	// md5
	43, 6, 1, 4, 1, 130, 55, 2, 1, 4, 	// msIndirectData
	43, 6, 1, 4, 1, 130, 55, 2, 1, 11, 	// msStatementType
	43, 6, 1, 4, 1, 130, 55, 2, 1, 12, 	// msSpOpusInfo
	43, 6, 1, 4, 1, 130, 55, 2, 1, 15, 	// msPeImageDataObjId
	43, 6, 1, 4, 1, 130, 55, 2, 1, 21, 	// msIndividualSPKeyPurpose
	43, 6, 1, 4, 1, 130, 55, 16, 4, 	// msOutlookExpress
	43, 6, 1, 5, 5, 7, 1, 1, 	// certAuthInfoAccess
	43, 14, 3, 2, 26, 	// sha1
	96, 134, 72, 1, 101, 3, 4, 2, 1, 	// sha256
	96, 134, 72, 1, 101, 3, 4, 2, 2, 	// sha384
	96, 134, 72, 1, 101, 3, 4, 2, 3, 	// sha512
	96, 134, 72, 1, 101, 3, 4, 2, 4, 	// sha224
	85, 4, 3, 	// commonName
	85, 4, 4, 	// surname
	85, 4, 6, 	// countryName
	85, 4, 7, 	// locality
	85, 4, 8, 	// stateOrProvinceName
	85, 4, 10, 	// organizationName
	85, 4, 11, 	// organizationUnitName
	85, 4, 12, 	// title
	85, 4, 13, 	// description
	85, 4, 41, 	// name
	85, 4, 42, 	// givenName
	85, 4, 43, 	// initials
	85, 4, 44, 	// generationalQualifier
	85, 29, 14, 	// subjectKeyIdentifier
	85, 29, 15, 	// keyUsage
	85, 29, 17, 	// subjectAltName
	85, 29, 18, 	// issuerAltName
	85, 29, 19, 	// basicConstraints
	85, 29, 31, 	// crlDistributionPoints
	85, 29, 32, 	// certPolicies
	85, 29, 35, 	// authorityKeyIdentifier
	85, 29, 37, 	// extKeyUsage
	42, 133, 3, 2, 2, 35, 1, 	// gostCPSignA
	42, 133, 3, 2, 2, 35, 2, 	// gostCPSignB
	42, 133, 3, 2, 2, 35, 3, 	// gostCPSignC
	42, 133, 3, 7, 1, 1, 1, 1, 	// gost2012PKey256
	42, 133, 3, 7, 1, 1, 1, 2, 	// gost2012PKey512
	42, 133, 3, 7, 1, 1, 2, 2, 	// gost2012Digest256
	42, 133, 3, 7, 1, 1, 2, 3, 	// gost2012Digest512
	42, 133, 3, 7, 1, 1, 3, 2, 	// gost2012Signature256
	42, 133, 3, 7, 1, 1, 3, 3, 	// gost2012Signature512
	42, 133, 3, 7, 1, 2, 1, 1, 1, 	// gostTC26Sign256A
	42, 133, 3, 7, 1, 2, 1, 1, 2, 	// gostTC26Sign256B
	42, 133, 3, 7, 1, 2, 1, 1, 3, 	// gostTC26Sign256C
	42, 133, 3, 7, 1, 2, 1, 1, 4, 	// gostTC26Sign256D
	42, 133, 3, 7, 1, 2, 1, 2, 1, 	// gostTC26Sign512A
	42, 133, 3, 7, 1, 2, 1, 2, 2, 	// gostTC26Sign512B
	42, 133, 3, 7, 1, 2, 1, 2, 3, 	// gostTC26Sign512C
	42, 129, 28, 207, 85, 1, 130, 45, 	// sm2
	42, 129, 28, 207, 85, 1, 131, 17, 	// sm3
	42, 129, 28, 207, 85, 1, 131, 117, 	// SM2_with_SM3
	42, 129, 28, 207, 85, 1, 131, 120, 	// sm3WithRSAEncryption
};

static const struct {
	unsigned char hash;
	enum OID oid : 8;
} oid_search_table[OID__NR] = {
	[  0] = {  10, OID_title                               }, // 55040c
	[  1] = {  19, OID_gostTC26Sign512C                    }, // 2a8503070102010203
	[  2] = {  19, OID_gostTC26Sign256D                    }, // 2a8503070102010104
	[  3] = {  23, OID_issuerAltName                       }, // 551d12
	[  4] = {  23, OID_initials                            }, // 55042b
	[  5] = {  29, OID_md2WithRSAEncryption                }, // 2a864886f70d010102
	[  6] = {  30, OID_md2                                 }, // 2a864886f70d0202
	[  7] = {  32, OID_id_dsa_with_sha1                    }, // 2a8648ce2e0403
	[  8] = {  35, OID_contentType                         }, // 2a864886f70d010903
	[  9] = {  35, OID_sha256WithRSAEncryption             }, // 2a864886f70d01010b
	[ 10] = {  36, OID_authorityKeyIdentifier              }, // 551d23
	[ 11] = {  37, OID_description                         }, // 55040d
	[ 12] = {  43, OID_id_dsa                              }, // 2a8648ce380401
	[ 13] = {  51, OID_msIndividualSPKeyPurpose            }, // 2b060104018237020115
	[ 14] = {  52, OID_SM2_with_SM3                        }, // 2a811ccf55018375
	[ 15] = {  54, OID_basicConstraints                    }, // 551d13
	[ 16] = {  54, OID_generationalQualifier               }, // 55042c
	[ 17] = {  60, OID_gostCPSignA                         }, // 2a850302022301
	[ 18] = {  60, OID_md3WithRSAEncryption                }, // 2a864886f70d010103
	[ 19] = {  64, OID_signed_data                         }, // 2a864886f70d010702
	[ 20] = {  77, OID_countryName                         }, // 550406
	[ 21] = {  77, OID_id_ecdsa_with_sha1                  }, // 2a8648ce3d0401
	[ 22] = {  83, OID_sha256                              }, // 608648016503040201
	[ 23] = {  84, OID_sm2                                 }, // 2a811ccf5501822d
	[ 24] = {  85, OID_smimeCapabilites                    }, // 2a864886f70d01090f
	[ 25] = {  87, OID_sha1                                }, // 2b0e03021a
	[ 26] = {  93, OID_gostCPSignB                         }, // 2a850302022302
	[ 27] = {  97, OID_email_address                       }, // 2a864886f70d010901
	[ 28] = { 106, OID_extKeyUsage                         }, // 551d25
	[ 29] = { 106, OID_msPeImageDataObjId                  }, // 2b06010401823702010f
	[ 30] = { 110, OID_locality                            }, // 550407
	[ 31] = { 124, OID_gost2012PKey256                     }, // 2a85030701010101
	[ 32] = { 126, OID_gostCPSignC                         }, // 2a850302022303
	[ 33] = { 126, OID_rsaEncryption                       }, // 2a864886f70d010101
	[ 34] = { 132, OID_smimeAuthenticatedAttrs             }, // 2a864886f70d010910020b
	[ 35] = { 142, OID_id_ecPublicKey                      }, // 2a8648ce3d0201
	[ 36] = { 142, OID_sha224WithRSAEncryption             }, // 2a864886f70d01010e
	[ 37] = { 143, OID_stateOrProvinceName                 }, // 550408
	[ 38] = { 145, OID_sm3WithRSAEncryption                }, // 2a811ccf55018378
	[ 39] = { 146, OID_subjectKeyIdentifier                }, // 551d0e
	[ 40] = { 157, OID_gost2012PKey512                     }, // 2a85030701010102
	[ 41] = { 157, OID_sha512                              }, // 608648016503040203
	[ 42] = { 160, OID_data                                }, // 2a864886f70d010701
	[ 43] = { 161, OID_crlDistributionPoints               }, // 551d1f
	[ 44] = { 173, OID_msOutlookExpress                    }, // 2b0601040182371004
	[ 45] = { 178, OID_sha384                              }, // 608648016503040202
	[ 46] = { 179, OID_keyUsage                            }, // 551d0f
	[ 47] = { 190, OID_gost2012Digest256                   }, // 2a85030701010202
	[ 48] = { 191, OID_gostTC26Sign256A                    }, // 2a8503070102010101
	[ 49] = { 195, OID_md4WithRSAEncryption                }, // 2a864886f70d010104
	[ 50] = { 198, OID_certPolicies                        }, // 551d20
	[ 51] = { 200, OID_msSpOpusInfo                        }, // 2b06010401823702010c
	[ 52] = { 201, OID_organizationName                    }, // 55040a
	[ 53] = { 204, OID_messageDigest                       }, // 2a864886f70d010904
	[ 54] = { 204, OID_sha384WithRSAEncryption             }, // 2a864886f70d01010c
	[ 55] = { 208, OID_gostTC26Sign512A                    }, // 2a8503070102010201
	[ 56] = { 208, OID_gostTC26Sign256B                    }, // 2a8503070102010102
	[ 57] = { 212, OID_name                                }, // 550429
	[ 58] = { 213, OID_commonName                          }, // 550403
	[ 59] = { 213, OID_sm3                                 }, // 2a811ccf55018311
	[ 60] = { 220, OID_md4                                 }, // 2a864886f70d0204
	[ 61] = { 223, OID_gost2012Signature256                }, // 2a85030701010302
	[ 62] = { 223, OID_gost2012Digest512                   }, // 2a85030701010203
	[ 63] = { 226, OID_sha1WithRSAEncryption               }, // 2a864886f70d010105
	[ 64] = { 227, OID_md5                                 }, // 2a864886f70d0205
	[ 65] = { 228, OID_certAuthInfoAccess                  }, // 2b06010505070101
	[ 66] = { 231, OID_msStatementType                     }, // 2b06010401823702010b
	[ 67] = { 234, OID_organizationUnitName                }, // 55040b
	[ 68] = { 237, OID_signingTime                         }, // 2a864886f70d010905
	[ 69] = { 237, OID_sha512WithRSAEncryption             }, // 2a864886f70d01010d
	[ 70] = { 240, OID_gost2012Signature512                }, // 2a85030701010303
	[ 71] = { 241, OID_gostTC26Sign512B                    }, // 2a8503070102010202
	[ 72] = { 241, OID_gostTC26Sign256C                    }, // 2a8503070102010103
	[ 73] = { 244, OID_surname                             }, // 550404
	[ 74] = { 245, OID_subjectAltName                      }, // 551d11
	[ 75] = { 245, OID_givenName                           }, // 55042a
	[ 76] = { 252, OID_sha224                              }, // 608648016503040204
	[ 77] = { 255, OID_msIndirectData                      }, // 2b060104018237020104
};
