#!/bin/sh
set -e
export DEBIAN_FRONTEND=none
. /usr/share/debconf/confmodule

db_get debian-installer/exit/always_halt
[ "$RET" = "true" ] && return 21
db_get debian-installer/exit/halt
[ "$RET" = "true" ] && return 21
db_get debian-installer/exit/poweroff
[ "$RET" = "true" ] && return 22

return 20
