#
# Makefile for the virtio-misc driver
#
virtio_misc-y := \
	virtio_misc_driver.o \
	virtio_misc_device.o \
	virtio_misc_vq.o \
	virtio_misc_vop.o \
	virtio_misc_rga.o \
	virtio_misc_helpers.o

obj-$(CONFIG_VIRTIO_MISC) += virtio_misc.o
